#!/bin/bash

# first parameter is csv file path (required)
# second parameter is path to result folder path (optional)

while IFS=, read -r lastName firstName
do
    firstNameFirstLetter=${firstName:0:01}

    russianLogin="${firstNameFirstLetter}${lastName}"

    traslitedLogin=$(echo "$russianLogin" | iconv -f utf-8 -t koi-7)

    lowerTranslitedLogin=${traslitedLogin,,}

    password=$(tr -dc A-Za-z0-9 </dev/urandom | head -c 10)

    [[ $2 = "" ]] && resultPath=$lowerTranslitedLogin || resultPath="$2/$lowerTranslitedLogin"

    #home directory cretates by default, shell bin/bash is default
    sudo useradd $lowerTranslitedLogin &&
    echo $lowerTranslitedLogin:$password | sudo chpasswd &&
    printf "userLogin: $lowerTranslitedLogin\npassword: $password" > $resultPath
    
done < $1