#!/bin/bash

if [[ -n "$1" && -f $1 ]]
    then
        read -p "Enter 1 if u wanna change file mod or 2 if u wanna change file owner? " answer
            if [[ $answer == 1 ]]
                then
                    read -p "Enter file modificators: " mods

                    sudo chmod $mods $1
            fi
            if [[ $answer == 2 ]]
                then
                    read -p "Enter new file owner: " owner

                    sudo chown $owner $1
            fi
    else
        echo "Error: file do not exists"

        exit 1
fi